const express = require('express');
const frontRouter = express.Router();
const userRouter = require("./user");
const findNavGood = require("./findNavGood");
const getCarousel = require("./getCarousel");
const getHot = require("./getHot");
const getSkillList = require("./getSkillList");
const getCategory = require("./getCategory");
const getDetial = require("./getDetial");
const order = require("./order");
frontRouter.use("/",userRouter);
frontRouter.use("/findNavGood",findNavGood);
frontRouter.use("/getCarousel",getCarousel);
frontRouter.use("/hot",getHot);
frontRouter.use("/skillList",getSkillList);
frontRouter.use("/getCategory",getCategory);
frontRouter.use("/getDetial",getDetial);
frontRouter.use("/order",order);
module.exports = frontRouter;
